name: haidai_flutter_module
description: A new Flutter module.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  dokit: ^0.8.0-nullsafety.0

  #图片库
  extended_image: ^4.0.0

  # add flutter_screenutil
  flutter_screenutil: ^5.0.0+2
  #  相册、拍照
  image_picker: ^0.7.5

  # 返回按钮拦截器
  back_button_interceptor: ^5.0.0

  equatable: ^2.0.0
  #  provider: 4.3.2+2
  get: ^4.3.5

  # 动态模型
  #  built_value: ^7.1.0
  #  built_collection: ^4.3.2
  # 网络请求
  dio: ^4.0.0
  # 基于dio的网络请求日志
  dio_log: ^2.0.0

  # toast
#  fluttertoast: ^7.1.6
  # 本地缓存
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  # 网络缓存图片(有缓存功能)
  #cached_network_image: ^3.0.0
  # 图片加载(可定义缩放等功能)
  #extended_image: ^4.0.1
  # 事件总线
  #event_bus: ^2.0.0
  # 下拉刷新、上拉加载
  flutter_easyrefresh: ^2.2.1
  # 日期选择控件
  #flutter_datetime_picker: ^1.5.0
  syncfusion_flutter_datepicker: ^19.2.44

  json_annotation: ^4.0.1
  #loading
  flutter_easyloading: ^3.0.0

  modal_bottom_sheet: ^2.0.0

  #common_util 工具类
  flustars: ^2.0.1
  #sqlite
  sqflite: ^2.0.0+3
  path: ^1.8.0
  #多线程
  isolate: ^2.1.0
  path_provider: ^2.0.2
  intl: ^0.17.0
  uuid: ^3.0.4

  image: ^3.0.2

  encrypt: ^5.0.0

  event_bus: ^2.0.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0

  #图表
  syncfusion_flutter_charts: ^19.2.51

  #设备
  device_info: ^2.0.2
  package_info: ^2.0.0

  better_video_player: ^1.1.5
  url_launcher: ^6.0.10
  #webview
  flutter_inappwebview: ^5.3.2
  screenshot: ^1.2.3

#  flutter_drag_scale:
#    git: https://github.com/LiuC520/flutter_drag_scale.git

dev_dependencies:
  flutter_test:
    sdk: flutter

  #  built_value_generator: ^7.1.0
  #  build_runner: ^1.10.2
  json_serializable: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add Flutter specific assets to your application, add an assets section,
  # like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add Flutter specific custom fonts to your application, add a fonts
  # section here, in this "flutter" section. Each entry in this list should
  # have a "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: com.flutter.haidai_flutter_module
    iosBundleIdentifier: com.flutter.haidaiFlutterModule

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - images/
